language: ruby
rvm:
  - 2.6.3
install:
  - gem install bundler:2.1.4
  - bundle install
before_script:
  - psql -c 'create database community_shield_server_test;' -U postgres
services:
  - postgresql
addons:
  postgresql: "11.3"
apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433
script:
  - RAILS_ENV=test bundle exec rails db:reset db:migrate
  - bundle exec rspec
