language: ruby
rvm:
  - 2.6.3
before_install:
  - psql -c 'create database community_shield_server_test;' -U postgres
addons:
  postgresql: "11.3"
apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433
script:
  - RAILS_ENV=test bundle exec rails db:reset db:migrate
  - bundle exec rspec
