language: ruby
rbenv:
  - 2.6.3
services:
  - postgresql
addons:
  postgresql: "11.3"
script:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sudo service postgresql start 11
  - sudo -u postgres psql -c 'create database travis_ci_test;'
  - RAILS_ENV=test bundle exec rails db:reset db:migrate
  - bundle exec rspec
